const routes = {
    home: "/",
    login: "/login",
    forgotPass: "/forgot-pass",
    resetPass: "/reset-pass",
    dashboard: "/dashboard",
    profile: "/profile",
    device: "/device",
    service: "/services",
    numberOrder: "/numerical-order",
    report: "/report",
    roleManagement: "/settings/role-management",
    accountManagement: "/settings/account-management",
    userLog: "/settings/user-log",
    addDevice: "/device/add-device",
    detailDevice: "/device/detail-device",
    updateDevice: "/device/update-device",
    addService: "/services/add-service",
    detailService: "/services/detail-service",
    updateService: "/services/update-service",
    addNewNumber: "/numerical-order/add-new-number",
    detailNumber: "/numerical-order/detail-number",
    addRole: "/settings/role-management/add-role",
    updateRole: "/settings/role-management/update-role",
    addAccount: "/settings/account-management/add-account",
    updateAccount: "/settings/account-management/update-account",
};

export default routes;
